apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  labels:
    machineconfiguration.openshift.io/role: worker
  name: 10-worker-iptables
spec:
  config:
    ignition:
      version: 2.2.0
    systemd:
      units:
      - name: iptables-contrail.service
        enabled: true
        contents: |
          [Unit]
          Description=Inserts iptables rules required by Contrail
          After=syslog.target
          AssertPathExists=/etc/contrail/iptables_script.sh

          [Service]
          Type=oneshot
          RemainAfterExit=yes
          ExecStart=/etc/contrail/iptables_script.sh
          StandardOutput=syslog
          StandardError=syslog

          [Install]
          WantedBy=basic.target
    storage:
      files:
      - filesystem: root
        path: /etc/contrail/iptables_script.sh
        mode: 0744
        user:
          name: root
        contents:
          # 'data:,' and base64 encoded scripts/iptables_script.sh 
          source: data:text/plain;charset=utf-8;base64,IyEvYmluL2Jhc2gKCnVkcD0oCjQ3ODkKODA1MwopCgp0Y3A9KAoxMDI1MAoxMDI1NgoxNTY3MgoxNTY3MwoxNzkKMTkzNgoyMDQ5CjIxODEKMjE4MgoyMzc5CjIzODAKMjU2NzIKMjU2NzMKMjU2ODQ6MjU2OTQKMjg4ODozODg4CjMwMDAKMzAwMgozMzMzCjM1MTQKNDM2OQo0NDMKNDczOQo0Nzg5CjQ4ODg6NTg4OAo1MTQKNTI2OQo1Mwo1NjcyCjU2NzMKNTkyMAo1OTIxCjU5OTUKNjM0Mwo2Mzc5CjYzODkKNzAwMAo3MDAxCjcwMTAKNzAxMQo3MDEyCjcwMTMKNzAxNAo3MjAwCjcyMDEKNzIwNAo4MAo4MAo4MDUzCjgwODAKODA4MQo4MDgyCjgwODMKODA4NAo4MDg1CjgwODYKODA4Nwo4MDg4CjgwODkKODA5MAo4MDkxCjgwOTIKODA5Mwo4MDk0CjgwOTYKODA5Nwo4MTAwCjgxMDEKODEwMgo4MTAzCjgxMDQKODEwOAo4MTEyCjgxMTMKODExNAo4MTQzCjgxODAKODE4MQo4NDQzCjg0NDQKOTAwMDoxMDAwMAo5MDQxCjkwNDIKOTA0NAo5MDUzCjkwOTAKOTA5MQo5MDkyCjkxNjAKOTE2MQo5MTY0CikKCmZ1bmN0aW9uIGFjY2VwdCgpewogIGxvY2FsIHByb3RvPSQxCiAgbG9jYWwgcAogIGxvY2FsIHRhYmxlPSRwcm90b1tAXQogIGZvciBwIGluICR7IXRhYmxlfTsgZG8KICAgIGVjaG8gIklORk86IGFkZCB1ZHAgJHAgaW50byBpdGFibGVzIgogICAgaXB0YWJsZXMgLXQgZmlsdGVyIC1JIElOUFVUIDEgLXcgNSAtVyAxMDAwMDAgLXAgJHByb3RvIC0tZHBvcnQgJHAgLWogQUNDRVBUCiAgZG9uZQp9CgphY2NlcHQgdGNwCmFjY2VwdCB1ZHAK
